name       : codelite
version    : 15.0.11
release    : 20
source     :
    - https://github.com/eranif/codelite/archive/refs/tags/15.0.11.tar.gz : d515327c8ab1c06a694ef2f40d07be7cc86707580e94d96c95c1a6b5fc7a27a9
homepage   : https://codelite.org/
component  : programming.ide
license    : GPL-2.0-or-later
summary    : CodeLite is an open source IDE for the C//C++ languages
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
