name       : codelite
version    : 9.0
release    : 1
source     :
    - https://github.com/eranif/codelite/archive/9.0.tar.gz : 401ce3c8394aaee661fcae01330e5934ddeb10f5e4abc671d77f06602db05398
license    : GPL-2.0
summary    : CodeLite is an open source IDE for the C//C++ languages.
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(python-2.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_CLANG=1 -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
