name       : codelite
version    : '11.0'
release    : 9
source     :
    - https://github.com/eranif/codelite/archive/11.0.tar.gz : 9eb23ea635fc746318a832efd752b08027c11efcd9af7f494f31dbaacdd651a1
component  : programming.ide
license    : GPL-2.0
summary    : CodeLite is an open source IDE for the C//C++ languages.
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
