name       : codelite
version    : 17.0.0
release    : 23
source     :
    - https://github.com/eranif/codelite/releases/download/17.0.0/codelite-17.0.0.tar.gz : c0dfe6df38426d761ef5622b7a9ab91481244a09ad751f5daafa37bb9b611d57
homepage   : https://codelite.org/
component  : programming.ide
license    : GPL-2.0-or-later
summary    : CodeLite is an open source IDE for the C//C++ languages
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -B build \
        -DENABLE_LLDB=0 \
        -DWITH_MYSQL=0 \
build      : |
    %make -C build
install    : |
    %make_install -C build
