name       : codelite
version    : 9.1
release    : 2
source     :
    - https://github.com/eranif/codelite/archive/9.1.tar.gz : 90ee7668b8be985cef9d4e19a0df49f6160dcb235a47a41620937ef431a9da6e
license    : GPL-2.0
summary    : CodeLite is an open source IDE for the C//C++ languages.
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(python-2.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_CLANG=1 -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
