name       : codelite
version    : '15.0'
release    : 18
source     :
    - https://github.com/eranif/codelite/archive/15.0.tar.gz : 9dd5679660a9d1a51186fcbb2d0d44655f0bc8bedeb2ee57b28c9776f139353f
component  : programming.ide
license    : GPL-2.0-or-later
summary    : CodeLite is an open source IDE for the C//C++ languages
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
