name       : codelite
version    : '12.0'
release    : 11
source     :
    - https://github.com/eranif/codelite/archive/12.0.tar.gz : e8912e3e0aea8890b5c65631ad94d58ddc587812c7ac6ec398e37aaa4b7005b4
component  : programming.ide
license    : GPL-2.0
summary    : CodeLite is an open source IDE for the C//C++ languages
description: |
    CodeLite is an open source IDE for the C//C++ languages.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(hunspell)
    - pkgconfig(libssh)
    - pkgconfig(ncursesw)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - wxwidgets-devel
setup      : |
    %cmake -DENABLE_LLDB=0 -DWITH_MYSQL=0 .
build      : |
    %make
install    : |
    %make_install
